### ISSUE TITLE
我在安装DOCKER时出现以下错误

### ISSUE THREAD

**Issue by cq134cq** [vastxie/NineAIQuickDeploy#11]
请问这是什么问题
root@linux:/ai/ai99# ls
docker-compose.yml
root@linux:/ai/ai99# docker-compose up -d
[+] Building 0.4s (1/1) FINISHED                                                                                                                                           docker:default
 => [nineai-open internal] load build definition from Dockerfile                                                                                                                     0.2s
 => => transferring dockerfile: 2B                                                                                                                                                   0.0s
failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
root@linux:/ai/ai99# docker-compose up -d
[+] Building 24.2s (9/10)                                                                                                                                                  docker:default
 => [nineai-open internal] load build definition from Dockerfile                                                                                                                     0.2s
 => => transferring dockerfile: 323B                                                                                                                                                 0.1s
 => [nineai-open internal] load metadata for docker.io/library/node:18-alpine                                                                                                        3.1s
 => [nineai-open internal] load .dockerignore                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                                      0.0s
 => [nineai-open internal] load build context                                                                                                                                        0.0s
 => => transferring context: 1.89kB                                                                                                                                                  0.0s
 => [nineai-open build 1/5] FROM docker.io/library/node:18-alpine@sha256:c7620fdecfefb96813da62519897808775230386f4c8482e972e37b8b18cb460                                           11.7s
 => => resolve docker.io/library/node:18-alpine@sha256:c7620fdecfefb96813da62519897808775230386f4c8482e972e37b8b18cb460                                                              0.0s
 => => sha256:ff171c16ee4e8ed3a0ae3edb6fb9558f281134a3879eedca7d79fc2e16e46073 40.25MB / 40.25MB                                                                                     8.2s
 => => sha256:7c215e7ef3945bd4fdac5a20f1e4a29c62f28c8493ad05d3e651d62cf069140d 2.34MB / 2.34MB                                                                                       1.4s
 => => sha256:3f72a72846173b6a02c1f73db9a74aca2af50fb39bf13ba2e4d12d13e5722d6c 451B / 451B                                                                                           0.3s
 => => sha256:c7620fdecfefb96813da62519897808775230386f4c8482e972e37b8b18cb460 1.43kB / 1.43kB                                                                                       0.0s
 => => sha256:17b35d6932abf679c57caa7b8297ded19d897606b92dcc415940c7690459d8c9 1.16kB / 1.16kB                                                                                       0.0s
 => => sha256:995e68c9d946f454675dd18204619ccd3b8e065f55f0ae1996f00300722554f9 7.14kB / 7.14kB                                                                                       0.0s
 => => extracting sha256:ff171c16ee4e8ed3a0ae3edb6fb9558f281134a3879eedca7d79fc2e16e46073                                                                                            2.7s
 => => extracting sha256:7c215e7ef3945bd4fdac5a20f1e4a29c62f28c8493ad05d3e651d62cf069140d                                                                                            0.1s
 => => extracting sha256:3f72a72846173b6a02c1f73db9a74aca2af50fb39bf13ba2e4d12d13e5722d6c                                                                                            0.0s
 => [nineai-open build 2/5] WORKDIR /app                                                                                                                                             0.3s
 => [nineai-open build 3/5] COPY . .                                                                                                                                                 0.1s
 => [nineai-open build 4/5] RUN npm install -g pnpm                                                                                                                                  5.9s
 => ERROR [nineai-open build 5/5] RUN pnpm install                                                                                                                                   2.5s
------                                                                                                                                                                                    
 > [nineai-open build 5/5] RUN pnpm install:                                                                                                                                              
2.354  ERR_PNPM_NO_PKG_MANIFEST  No package.json found in /app                                                                                                                            
------                                                                                                                                                                                    
failed to solve: process "/bin/sh -c pnpm install" did not complete successfully: exit code: 1                                                                                            
root@linux:/ai/ai99#

**Comment by cq134cq** [comment]
root@linux:/ai/ai99# ll
total 20
drwxr-xr-x  2 root root 4096 Mar 18 02:51 ./
drwxr-xr-x 13 root root 4096 Mar 18 02:46 ../
-rw-r--r--  1 root root 1012 Mar 18 02:46 docker-compose.yml
-rw-r--r--  1 root root  284 Mar 18 02:51 Dockerfile
-rw-r--r--  1 root root  465 Mar 18 02:47 .env.example

**Comment by vastxie** [comment]
对应.env里的数据库配置有修改么

**Comment by KenGrofork** [comment]
你这很明显没有项目文件
