### ISSUE TITLE
作者你好，我在docker部署完成后

### ISSUE THREAD

**Issue by 1487879421888** [vastxie/NineAIQuickDeploy#12]
作者，你好，我在docker compose部署完成之后，打开页面，显示无法访问页面。如图。
![image](https://github.com/vastxie/99AI/assets/47622641/f80341e5-4259-49f9-b2ee-0358c6c94047)
![image](https://github.com/vastxie/99AI/assets/47622641/f81ce5d0-dc86-48b9-8f75-0dc0ed21bc6d)
然后，这些容器时不时的会自动重启，端口也是开放的，不知道什么原因。
![image](https://github.com/vastxie/99AI/assets/47622641/6c565375-c70f-4ea9-be46-df19d8d95dae)

**Comment by vastxie** [comment]
收否对应改了.env里的数据库配置

**Comment by mmw1984** [comment]
+1
不过我显示的是wrong pass
