### ISSUE TITLE
思维导图 出错，说未找到匹配的模型，请重新选择模型！

### ISSUE THREAD

**Issue by cq134cq** [vastxie/NineAIQuickDeploy#17]
思维导图 出错，说未找到匹配的模型，请重新选择模型！
请问应当在那里配置？

**Comment by vastxie** [comment]
模型配置，特殊模型里面

**Comment by coolbeiyu1** [comment]
特殊模型加了还是说未找到模型

**Comment by cq134cq** [comment]
> 模型配置，特殊模型里面
我以配特殊模型，可是还是报说未找到匹配的模型，请重新选择模型
![C2108182-3DBB-4982-B43E-765607496BFE](https://github.com/vastxie/99AI/assets/95132993/004cb231-f99e-4ab5-8d67-55471a8d4252)

**Comment by xiaohuakang** [comment]
同问，思维导图这里应该选择什么模型呢？
