### ISSUE TITLE
专业绘图失败

### ISSUE THREAD

**Issue by 675061370** [vastxie/NineAIQuickDeploy#2]
0|nineai-v2.4.5  | 2024-01-24 15:10:13: [Nest] 4470  - 01/24/2024, 3:10:13 PM   DEBUG [MidjourneyService] 本次绘图指令为[f1fee638d] 博美  --v 6.0 --s 100 --ar 9:16 --c 0 --q 1
0|nineai-v2.4.5  | 2024-01-24 15:10:13: [Nest] 4470  - 01/24/2024, 3:10:13 PM   ERROR [MidjourneyService] 发送绘画指令失败
0|nineai-v2.4.5  | 2024-01-24 15:10:13: error:  HttpException: 发送绘图指令失败、请联系管理员检测绘画配置！
0|nineai-v2.4.5  |     at MidjourneyService.sendDrawCommand (/www/wwwroot/ai/dist/modules/midjourney/midjourney.service.js:185:19)
0|nineai-v2.4.5  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|nineai-v2.4.5  |     at async MidjourneyService.draw (/www/wwwroot/ai/dist/modules/midjourney/midjourney.service.js:52:17)
0|nineai-v2.4.5  |     at async QueueProcessor.handleJob (/www/wwwroot/ai/dist/modules/queue/queue.process.js:23:21)
0|nineai-v2.4.5  |     at async /www/wwwroot/ai/node_modules/.pnpm/bull@4.12.2/node_modules/bull/lib/p-timeout.js:69:17 {
0|nineai-v2.4.5  |   response: '发送绘图指令失败、请联系管理员检测绘画配置！',
0|nineai-v2.4.5  |   status: 400,
0|nineai-v2.4.5  |   options: undefined
0|nineai-v2.4.5  | }

**Comment by vastxie** [comment]
已更新mj-proxy-plus支持
