### ISSUE TITLE
模型设置确定后返回还是空白，设置的模型也没了

### ISSUE THREAD

**Issue by zhao316678171** [vastxie/NineAIQuickDeploy#21]
以kimi为例：
![image](https://github.com/vastxie/99AI/assets/63034357/06880163-d45e-4545-bb3e-3769f2dc0f6e)
确定后
![image](https://github.com/vastxie/99AI/assets/63034357/165e11cc-1a91-43bb-b7d3-3dd8d5163192)
重新读取模型设置界面，刚才设置的没有出来，请各位大佬看看什么原因？

**Comment by zhao316678171** [comment]
![image](https://github.com/vastxie/99AI/assets/63034357/1e09a45a-3aac-447b-856a-ace439858a8f)
模型全局配置了自己架设的one api，不知道是不是因为这个原因？

**Comment by vastxie** [comment]
检查后台日志
