### ISSUE TITLE
提一些小小的意见

### ISSUE THREAD

**Issue by QRICHQ** [vastxie/NineAIQuickDeploy#23]
1.可以增加一个本地储存的选项吗
2.gpts可以通过类似gptshunter这种网站上同步吗
3.用户可以自己创建应用，管理者审核
4.可以在管理页选择，对话的标题可以直接取对话的前几个字，就不用调用默认模型浪费了一小点余额了
谢谢大佬了

**Comment by vastxie** [comment]
1会考虑
