### ISSUE TITLE
非常无语非常糟糕的项目

### ISSUE THREAD

**Issue by time-demon** [vastxie/NineAIQuickDeploy#30]
我全部安装流程安装的，最终安装成功也启动成功，9520端口也显示成功，但就是访问不了，非常糟糕的项目，一点都不人性化，即使按着他的流程来也运行不了，非常极度的糟糕，我这辈子真的没这么气愤过

**Comment by vastxie** [comment]
你好，这边建议别用 /吃瓜

**Comment by cybergoudan** [comment]
自己不行就反思一下自己  要不就用钞能力
