### ISSUE TITLE
请问API的白名单在那个版本取消了？

### ISSUE THREAD

**Issue by cq134cq** [vastxie/NineAIQuickDeploy#32]
### 核心例行检查

- [x] 我已经在 issue 中搜索了我的问题答案，并确认目前没有类似 issue
- [x] 我已确认已升级到最新版本
- [x] 我已完整查看过项目 README
- [x] 我已尝试通过询问 AI 或网络搜索检索我的问题
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
请问API的白名单在那个版本取消了？
**复现步骤**

**相关日志**

**相关截图**
如果没有的话，请删除此节。

**Comment by vastxie** [comment]
有API白名单的版本不存在
