### ISSUE TITLE
chatTitle获取失败，导致应用重启

### ISSUE THREAD

**Issue by waloyn** [vastxie/NineAIQuickDeploy#34]
### 核心例行检查

- [x] 我已经在 issue 中搜索了我的问题答案，并确认目前没有类似 issue
- [x] 我已确认已升级到最新版本
- [x] 我已完整查看过项目 README
- [x] 我已尝试通过询问 AI 或网络搜索检索我的问题
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
更新3.5.0后，前端表现为新会话提示接口错误，继续更新前的旧会话正常，一旦前端提示接口异常，后端应用立即重启。

1.前端提示如图：
![1](https://github.com/vastxie/99AI/assets/20416585/d3aa2336-4f4d-4388-a39a-07170c603b2b)
2.后端日志如图：
![2](https://github.com/vastxie/99AI/assets/20416585/d4cf546c-6e5f-4e37-b23e-e8dd9c182f36)

**复现步骤**
更新3.5.0后点击新会话
**相关日志**
`ChatService
error:  TypeError: Cannot read properties of undefined (reading '0')
    at OpenAIChatService.chatFree (/app/dist/modules/ai/openaiChat.service.js:133:125)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatService.updateChatTitle (/app/dist/modules/chat/chat.service.js:661:33)
[Nest] 1  - 07/11/2024, 3:12:58 PM     LOG 当前标题是undefined
[Nest] 1  - 07/11/2024, 3:12:58 PM     LOG undefined
/app/dist/modules/chat/chat.service.js:671
            if (chatTitle.length > 15) {
                          ^

TypeError: Cannot read properties of undefined (reading 'length')
    at ChatService.updateChatTitle (/app/dist/modules/chat/chat.service.js:671:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.14.0
 current use version in ------>:  3.5.0
[Nest] 1  - 07/11/2024, 3:13:04 PM     LOG [NestFactory] Starting Nest application...`

日志中的当前标题是临时加的输出。

我的临时解决方法：
将chat.service.js中671行的代码替换
`
if (chatTitle.length > 15) {
     chatTitle = chatTitle.slice(0, 15);
 }
`
替换为：

`
chatTitle = typeof chatTitle === 'undefined' ? 'NewChat' : chatTitle.slice(0, 15);
`

**Comment by vastxie** [comment]
截取位置放错了，应该放在前面的try里面，已修复。另外，出现这种问题，一般是全局模型调用失败，需要检查下全局模型的配置。
