### ISSUE TITLE
群晖部署出错，希望作者适配下

### ISSUE THREAD

**Issue by zzfree2021** [vastxie/NineAIQuickDeploy#42]
使用的群晖7.1，自带docker，建立了相关目录99ai，下载了docker-compose.yml和dockerfile文件，在ssh下编译出错
![image](https://github.com/user-attachments/assets/c9aa8ffa-39c6-4547-926b-5355a747055a)
跟nas兼容有问题还是怎么？

**Comment by Kerrbty** [comment]
下载zip包安装试试，源码里面 package.json 是存在的，报错的缺文件
