### ISSUE TITLE
【bug】无法上传应用logo

### ISSUE THREAD

**Issue by taurusduan** [vastxie/NineAIQuickDeploy#6]
无法上传应用logo

![image](https://github.com/vastxie/NineAIQuickDeploy/assets/30854760/95a14bd6-3bac-40b1-a259-3dcf79adc56c)
点击上传之后就没有反应了。确定以后也是无法加载。

**Comment by shanzhengfei** [comment]
因为没有配存储，控制台能看到报错，不过这个应该添加个提示
