### ISSUE TITLE
依赖报销怎么办?

### ISSUE THREAD

**Issue by CNOO1** [vastxie/NineAIQuickDeploy#8]
dependencies:
- @nestjs/platform-express 7.6.18
+ @nestjs/platform-express 9.4.3 (10.3.3 is available)

 WARN  Issues with peer dependencies found
.
└─┬ nestjs-redis 1.3.3
  └─┬ @nestjs/core 7.6.18
    └── ✕ unmet peer @nestjs/platform-express@^7.0.0: found 9.4.3

**Comment by vastxie** [comment]
warn 请无视
